//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerButtonLeft
        {
            get
            {
                return SteamVR_Actions.default_LowerButtonLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerButtonRight
        {
            get
            {
                return SteamVR_Actions.default_LowerButtonRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpperButtonLeft
        {
            get
            {
                return SteamVR_Actions.default_UpperButtonLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpperButtonRight
        {
            get
            {
                return SteamVR_Actions.default_UpperButtonRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean NorthLeftHand
        {
            get
            {
                return SteamVR_Actions.default_NorthLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean NorthRightHand
        {
            get
            {
                return SteamVR_Actions.default_NorthRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SouthLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SouthLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SouthRightHand
        {
            get
            {
                return SteamVR_Actions.default_SouthRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean EastLeftHand
        {
            get
            {
                return SteamVR_Actions.default_EastLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean EastRightHand
        {
            get
            {
                return SteamVR_Actions.default_EastRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean WestLeftHand
        {
            get
            {
                return SteamVR_Actions.default_WestLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean WestRightHand
        {
            get
            {
                return SteamVR_Actions.default_WestRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean StickClick
        {
            get
            {
                return SteamVR_Actions.default_StickClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
